### ISSUE TITLE
No processes shown with PSUtil 3 and PSUtil 4

### ISSUE THREAD

**Issue by dsreyes1014** [JeffHoogland/Exterminator#2]
I'm on Gentoo and when I open the app it just shows a frozen cpu and memory bar with no processes running.  Just a progressbar bouncing back and forth.

**Comment by JeffHoogland** [comment]
What version of python / psutil are you using? Any output in terminal when you run exterminator from there?

**Comment by dsreyes1014** [comment]
python 2.7 and psutil-3.4.2.  I'll post output in a bit.

**Comment by dsreyes1014** [comment]
Here's the terminal output:

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/exterminator", line 128, in threadFunc
    func()
  File "/usr/bin/exterminator", line 307, in getPsUtilData
    tmp = psutil.get_process_list()
AttributeError: module 'psutil' has no attribute 'get_process_list'`

**Comment by dsreyes1014** [comment]
I'm assuming you're requiring psutil-4.0.0?....

**Comment by JeffHoogland** [comment]
Actually - Exterminator supports PSUtil 1.x and 2.x. Didn't know a 3.x had been released. Really annoying that they broke their API again. Not sure I want to support a 3rd version of this library.

**Comment by dsreyes1014** [comment]
Ok no worries.  I really appreciate your work using EFL.  ePad is great too.  I'm creating ebuilds for gentoo systems with these apps so if you do end up restructuring your code for psutil-3.x or the now psutil-4.x let me know so I can update it for gentoo installs.

**Comment by JeffHoogland** [comment]
Alrighty - I'll leave this open and if time permits look into the new API for PSUtil. If Gentoo has versions 1 or 2 in the repos that can be forced to use it should work as expected for you.

My current dev system is still Ubuntu 14.04 based, but it looks like Ubuntu 16.04 is going to use PSUtil 3.4.x - so I'll get it working with that before I upgrade to 16.04 later this year.

**Comment by dsreyes1014** [comment]
Sounds great Jeff!!  Thanks for your help.  I just installed a downgraded version of psutil to version 2.1.3 and all is working on my system so far.  So it's a workaround for now.

**Comment by NuLogicSystems** [comment]
Same issue on Arch:
$ ./exterminator
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(_self._args, *_self._kwargs)
  File "./exterminator", line 128, in threadFunc
    func()
  File "./exterminator", line 314, in getPsUtilData
    tmp = psutil.get_process_list()
AttributeError: module 'psutil' has no attribute 'get_process_list'

python-psutil 4.3.0

**Comment by JeffHoogland** [comment]
Downgrade your psutil library to version 2.x and it will work as expected.

**Comment by NuLogicSystems** [comment]
Not really an option on Arch, but lxtask, gnome-system-monitor, mate-system-monitor or mate-system-monitor-gtk3 will do for now.

**Comment by JeffHoogland** [comment]
This should be resolves via https://github.com/JeffHoogland/Exterminator/commit/fc7c8547bb746eac1233ce01ea9d71e224e43d69

**Comment by NuLogicSystems** [comment]
Cool, I will build and test this out later today when I am back home.
